# Generated by Django 4.2.7 on 2024-01-29 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='doer',
        ),
    ]
